apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whatsapp-mcp
resources:
  - ../../base
patches:
  - path: patch-env.yaml
  - path: patch-image.yaml
images:
  - name: harbor.e-dani.com/homelab/whatsappmcp-whatsapp-connector
    digest: sha256:6a0789feb3fe2b268659508bbab259cfdf4a997513f83bc58fa181245aa67aae
  - name: harbor.e-dani.com/homelab/whatsappmcp-whatsapp-cloud-connector
    newTag: latest
  - name: harbor.e-dani.com/homelab/whatsappmcp-telegram-connector
    newTag: latest
  - name: harbor.e-dani.com/homelab/whatsappmcp-telegram-sync
    newTag: latest
  - name: harbor.e-dani.com/homelab/whatsappmcp-instagram-connector
    newTag: latest
  - name: harbor.e-dani.com/homelab/whatsappmcp-mcp-server
    newTag: v1.3.6
    digest: sha256:9220729bb1d9a1076e7e262e9ed0159b9b37955ad70ce46002e9ae453a12b674
  - name: harbor.e-dani.com/homelab/whatsappmcp-auto-reply-worker
    newTag: latest
