apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-connector
  namespace: whatsapp-mcp
spec:
  template:
    spec:
      containers:
        - name: whatsapp-connector
          image: harbor.e-dani.com/homelab/whatsappmcp-whatsapp-connector:v1.3.13
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-cloud-connector
  namespace: whatsapp-mcp
spec:
  template:
    spec:
      containers:
        - name: whatsapp-cloud-connector
          image: harbor.e-dani.com/homelab/whatsappmcp-whatsapp-cloud-connector:v1.3.12@sha256:77129373fc7f5e7b2417c50e9ac6674b3ea90c5cfb9bd2aacadd09e4d9d8fd6a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: instagram-connector
  namespace: whatsapp-mcp
spec:
  template:
    spec:
      containers:
        - name: instagram-connector
          image: harbor.e-dani.com/homelab/whatsappmcp-instagram-connector:v1.3.12@sha256:33d980dc270af8a6942a762c122428712250714e35003f7435e7f47d2f91aa07
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-connector
  namespace: whatsapp-mcp
spec:
  template:
    spec:
      containers:
        - name: telegram-connector
          image: harbor.e-dani.com/homelab/whatsappmcp-telegram-connector:v1.3.12@sha256:f3c0593c82924efcf779fa5db9d49fbac8b55f8d63e75fb4d2a0626e441a8074
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
  namespace: whatsapp-mcp
spec:
  template:
    spec:
      containers:
        - name: mcp-server
          image: harbor.e-dani.com/homelab/whatsappmcp-mcp-server:v1.3.12@sha256:2a1b075bc3088644e558661780bde209c43953ca6c7ccd562cad947459d84103
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-sync
  namespace: whatsapp-mcp
spec:
  template:
    spec:
      containers:
        - name: telegram-sync
          image: harbor.e-dani.com/homelab/whatsappmcp-telegram-sync:latest
